# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

RUST_MIN_VER="1.92"

inherit cargo desktop git-r3 optfeature xdg

DESCRIPTION="GTK4/libadwaita app store for Gentoo Portage, with a CLI companion"
HOMEPAGE="https://github.com/tarilka0gg/portage-store"
EGIT_REPO_URI="https://github.com/tarilka0gg/portage-store.git"

LICENSE="GPL-2"
# Dependent crate licenses (generated by packaging/gentoo/gen-ebuild-data.py)
LICENSE+=" Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-3.0 Unlicense"
SLOT="0"

IUSE="webview"

# doas runs the root-owned helper (resources/priv-helper.sh); eix feeds the package index
RDEPEND="
	app-admin/doas
	app-portage/eix
	>=gui-libs/gtk-4.12:4
	>=gui-libs/libadwaita-1.5:1
	webview? ( net-libs/webkit-gtk:6 )
"
DEPEND="
	>=gui-libs/gtk-4.12:4
	>=gui-libs/libadwaita-1.5:1
	webview? ( net-libs/webkit-gtk:6 )
"
BDEPEND="virtual/pkgconfig"

QA_FLAGS_IGNORED="usr/bin/${PN} usr/bin/${PN}-cli"

pkg_setup() {
	rust_pkg_setup
}

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}

src_configure() {
	local myfeatures=( $(usev webview) )
	cargo_src_configure
}

src_install() {
	cargo_src_install

	# Privileged helper: one root-owned script behind a single passwordless doas rule
	exeinto /usr/libexec/${PN}
	newexe resources/priv-helper.sh priv-helper
	doexe resources/sandbox-build.sh

	# The helper appends to its audit log; it only needs the directory.
	# Group ownership (root:portage, so portage-group users can read the log) is set in
	# pkg_postinst: it does not survive into the merged image from here.
	keepdir /var/log/${PN}
	fperms 0750 /var/log/${PN}

	domenu packaging/io.github.tarilka0gg.PortageStore.desktop
	insinto /usr/share/metainfo
	doins packaging/io.github.tarilka0gg.PortageStore.metainfo.xml
	insinto /usr/share/icons/hicolor/scalable/apps
	doins packaging/icons/io.github.tarilka0gg.PortageStore.svg
	einstalldocs
}

pkg_postinst() {
	xdg_pkg_postinst
	chgrp portage "${EROOT}/var/log/${PN}" || ewarn "could not set the group of /var/log/${PN}"
	optfeature "Flatpak lane (apps outside the tree)" sys-apps/flatpak

	elog "portage-store needs a passwordless doas rule for its privileged helper,"
	elog "otherwise installs and USE-flag changes will fail. Add to /etc/doas.conf"
	elog "(adjust the user name):"
	elog
	elog "  permit nopass YOUR_USER cmd /usr/libexec/${PN}/priv-helper"
	elog
	elog "This is deliberately not done by the ebuild: a package must not edit"
	elog "system auth files. See the header of resources/priv-helper.sh for what"
	elog "the rule does and does not trust."
}

pkg_postrm() {
	xdg_pkg_postrm
}
