# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

CRATES="
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.104
	async-channel@2.5.0
	autocfg@1.5.1
	bitflags@2.13.1
	bstr@1.13.0
	bytes@1.12.1
	cairo-rs@0.22.0
	cairo-sys-rs@0.22.0
	cfg-expr@0.20.8
	cfg-if@1.0.4
	clap@4.6.6
	clap_builder@4.6.6
	clap_derive@4.6.4
	clap_lex@1.1.0
	colorchoice@1.0.5
	concurrent-queue@2.5.0
	crossbeam-utils@0.8.22
	equivalent@1.0.2
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.2
	field-offset@0.3.6
	futures-channel@0.3.33
	futures-core@0.3.33
	futures-executor@0.3.33
	futures-io@0.3.33
	futures-macro@0.3.33
	futures-task@0.3.33
	futures-util@0.3.33
	gdk-pixbuf-sys@0.22.0
	gdk-pixbuf@0.22.0
	gdk4-sys@0.11.4
	gdk4@0.11.4
	gio-sys@0.22.8
	gio@0.22.8
	glib-macros@0.22.6
	glib-sys@0.22.8
	glib@0.22.8
	gobject-sys@0.22.6
	graphene-rs@0.22.8
	graphene-sys@0.22.8
	gsk4-sys@0.11.4
	gsk4@0.11.4
	gtk4-macros@0.11.4
	gtk4-sys@0.11.4
	gtk4@0.11.4
	hashbrown@0.17.1
	heck@0.5.0
	indexmap@2.14.0
	is_terminal_polyfill@1.70.2
	itoa@1.0.18
	javascriptcore6-sys@0.6.0
	javascriptcore6@0.6.0
	libadwaita-sys@0.9.2
	libadwaita@0.9.2
	libc@0.2.189
	lock_api@0.4.14
	memchr@2.8.3
	memoffset@0.9.1
	mio@1.2.2
	once_cell_polyfill@1.70.2
	pango-sys@0.22.0
	pango@0.22.8
	parking@2.2.1
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	pin-project-lite@0.2.17
	pkg-config@0.3.33
	proc-macro-crate@3.5.0
	proc-macro2@1.0.107
	quick-xml@0.41.0
	quote@1.0.47
	redox_syscall@0.5.18
	rustc_version@0.4.1
	scopeguard@1.2.0
	semver@1.0.28
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_json@1.0.151
	serde_spanned@1.1.1
	signal-hook-registry@1.4.8
	similar@3.1.2
	slab@0.4.12
	smallvec@1.15.2
	socket2@0.6.5
	soup3-sys@0.9.0
	soup3@0.9.0
	strsim@0.11.1
	syn@2.0.119
	syn@3.0.3
	system-deps@7.0.8
	target-lexicon@0.13.5
	tokio-macros@2.7.2
	tokio@1.53.1
	toml@1.1.4+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.13+spec-1.1.0
	toml_parser@1.1.3+spec-1.1.0
	toml_writer@1.1.2+spec-1.1.0
	unicode-ident@1.0.24
	utf8parse@0.2.2
	version-compare@0.2.1
	wasi@0.11.1+wasi-snapshot-preview1
	webkit6-sys@0.6.0
	webkit6@0.6.1
	windows-link@0.2.1
	windows-sys@0.61.2
	winnow@1.0.4
	zmij@1.0.23
"
RUST_MIN_VER="1.92"

inherit cargo desktop optfeature xdg

DESCRIPTION="GTK4/libadwaita app store for Gentoo Portage, with a CLI companion"
HOMEPAGE="https://github.com/tarilka0gg/portage-store"
SRC_URI="
	https://github.com/tarilka0gg/portage-store/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-2"
# Dependent crate licenses (generated by packaging/gentoo/gen-ebuild-data.py)
LICENSE+=" Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-3.0 Unlicense"
SLOT="0"
KEYWORDS="~amd64"
IUSE="webview"

# doas runs the root-owned helper (resources/priv-helper.sh); eix feeds the package index
RDEPEND="
	app-admin/doas
	app-portage/eix
	>=gui-libs/gtk-4.12:4
	>=gui-libs/libadwaita-1.5:1
	webview? ( net-libs/webkit-gtk:6 )
"
DEPEND="
	>=gui-libs/gtk-4.12:4
	>=gui-libs/libadwaita-1.5:1
	webview? ( net-libs/webkit-gtk:6 )
"
BDEPEND="virtual/pkgconfig"

QA_FLAGS_IGNORED="usr/bin/${PN} usr/bin/${PN}-cli"

pkg_setup() {
	rust_pkg_setup
}

src_configure() {
	local myfeatures=( $(usev webview) )
	cargo_src_configure
}

src_install() {
	cargo_src_install

	# Privileged helper: one root-owned script behind a single passwordless doas rule
	exeinto /usr/libexec/${PN}
	newexe resources/priv-helper.sh priv-helper
	doexe resources/sandbox-build.sh

	# The helper appends to its audit log; it only needs the directory.
	# Group ownership (root:portage, so portage-group users can read the log) is set in
	# pkg_postinst: it does not survive into the merged image from here.
	keepdir /var/log/${PN}
	fperms 0750 /var/log/${PN}

	domenu packaging/io.github.tarilka0gg.PortageStore.desktop
	insinto /usr/share/metainfo
	doins packaging/io.github.tarilka0gg.PortageStore.metainfo.xml
	insinto /usr/share/icons/hicolor/scalable/apps
	doins packaging/icons/io.github.tarilka0gg.PortageStore.svg
	einstalldocs
}

pkg_postinst() {
	xdg_pkg_postinst
	chgrp portage "${EROOT}/var/log/${PN}" || ewarn "could not set the group of /var/log/${PN}"
	optfeature "Flatpak lane (apps outside the tree)" sys-apps/flatpak

	elog "portage-store needs a passwordless doas rule for its privileged helper,"
	elog "otherwise installs and USE-flag changes will fail. Add to /etc/doas.conf"
	elog "(adjust the user name):"
	elog
	elog "  permit nopass YOUR_USER cmd /usr/libexec/${PN}/priv-helper"
	elog
	elog "This is deliberately not done by the ebuild: a package must not edit"
	elog "system auth files. See the header of resources/priv-helper.sh for what"
	elog "the rule does and does not trust."
}

pkg_postrm() {
	xdg_pkg_postrm
}
